name: CD - Deploy Lambda Functions

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-west-3
  S3_BUCKET: oes-lambda-deploy-eu-west-3
  CONVERT_LAMBDA_NAME: convert-json-to-parquet
  INGEST_LAMBDA_NAME: oes-lambda-ingest-eu-west-3-dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Checkout code
        uses: actions/checkout@v3

      - name: ğŸ Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: ğŸ“¦ Install production dependencies
        run: |
          python -m pip install --upgrade pip
          mkdir -p package
          pip install -r requirements.txt -t package/

      - name: ğŸ§ª Run unit tests
        run: python -m unittest discover tests

      - name: ğŸ“ Zip Ingest Lambda
        run: |
          cd lambda/ingest
          zip -r ../../../ingest_function.zip ./*
          cd ../../

      - name: ğŸ“ Zip Convert Lambda
        run: |
          cd lambda/convert
          zip -r ../../../convert_function.zip ./*
          cd ../../

      - name: ğŸ” Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: ${{ env.AWS_REGION }}

      - name: â˜ï¸ Upload Convert ZIP to S3
        run: |
          aws s3 cp convert_function.zip s3://${{ env.S3_BUCKET }}/convert_function.zip

      - name: â˜ï¸ Upload Ingest ZIP to S3
        run: |
          aws s3 cp ingest_function.zip s3://${{ env.S3_BUCKET }}/ingest_function.zip

      - name: ğŸš€ Deploy Convert Lambda from S3
        run: |
          aws lambda update-function-code \
            --function-name ${{ env.CONVERT_LAMBDA_NAME }} \
            --s3-bucket ${{ env.S3_BUCKET }} \
            --s3-key convert_function.zip

      - name: ğŸš€ Deploy Ingest Lambda from S3
        run: |
          aws lambda update-function-code \
            --function-name ${{ env.INGEST_LAMBDA_NAME }} \
            --s3-bucket ${{ env.S3_BUCKET }} \
            --s3-key ingest_function.zip
